version: "3"
services:
  jupyter-lab:
    build:
      context: .
      dockerfile: Dockerfile
    image: h1royuki229/plotly
    command: jupyter-lab --ip=0.0.0.0 --port=8892 --no-browser --allow-root --NotebookApp.token='' --notebook-dir=/workdir
    ports:
      - "8892:8892"
      - "8050:8050"
    volumes:
      - .:/workdir
  jupyter-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    image: h1royuki229/plotly
    command: jupyter notebook --ip=0.0.0.0 --port=8893 --no-browser --allow-root --NotebookApp.token='' --notebook-dir=/workdir
    ports:
      - "8893:8893"
      # - "8050:8050"
    volumes:
      - .:/workdir
